export const STARSHIPS = {
  '2': 'CR90 corvette',
  '3': 'Star Destroyer',
  '5': 'Sentinel-class landing craft',
  '9': 'Death Star',
  '10': 'Millennium Falcon',
  '11': 'Y-wing',
  '12': 'X-wing',
  '13': 'TIE Advanced x1',
  '15': 'Executor',
  '17': 'Rebel transport',
  '21': 'Slave 1',
  '22': 'Imperial shuttle',
  '23': 'EF76 Nebulon-B escort frigate',
  '27': 'Calamari Cruiser',
  '28': 'A-wing',
  '29': 'B-wing',
  '31': 'Republic Cruiser',
  '32': 'Droid control ship',
  '39': 'Naboo fighter',
  '40': 'Naboo Royal Starship',
  '41': 'Scimitar',
  '43': 'J-type diplomatic barge',
  '47': 'AA-9 Coruscant freighter',
  '48': 'Jedi starfighter',
  '49': 'H-type Nubian yacht',
  '52': 'Republic Assault ship',
  '58': 'Solar Sailer',
  '59': 'Trade Federation cruiser',
  '61': 'Theta-class T-2c shuttle',
  '63': 'Republic attack cruiser',
  '64': 'Naboo star skiff',
  '65': 'Jedi Interceptor',
  '66': 'arc-170',
  '68': 'Banking clan frigte',
  '74': 'Belbullab-22 starfighter',
  '75': 'V-wing',
};
